services:
  app:
    build: .
    image: keboola/ex-ftp
    volumes:
      - ./tests/ftpInitContent:/code/tests/ftpInitContent
      - ssh-keys:/root/.ssh:ro
    links:
      - sshproxy
      - ftp

  dev: &devConfig
    build: .
    volumes:
      - ./:/code
      - ./data:/data
      - ssh-keys:/root/.ssh:ro
    links:
      - sshproxy
      - ftp

  ftp:
    image: rreignier/pure-ftpd
    environment:
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: userpass
      FTP_USER_HOME: /home/ftpusers/
      FTP_PASSIVE_PORTS: 10000:10005
      PUBLICHOST: ftp
    volumes:
      - ./tests/ftpInitContent:/home/ftpusers

  sshproxy:
    image: keboola/db-component-ssh-proxy:latest
    volumes:
      - ssh-keys:/root/.ssh
    links:
      - ftp

volumes:
  ssh-keys: