version: '2'
services:
  dev:
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    links:
      - ftp
  ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: userpass
      FTP_USER_HOME: /home/ftpusers/
      PUBLICHOST: ftp

